# See options at https://github.com/coogie/oscailte
# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://www.home-assistant.io
title: Home Assistant
subtitle: Open source home automation that puts local control and privacy first.
author: Home Assistant
simple_search: https://www.google.com/search
description: >-
  Open source home automation that puts local control and privacy first.
  Powered by a worldwide community of tinkerers and DIY enthusiasts.
  Perfect to run on a Raspberry Pi or a local server.

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

permalink: /blog/:year/:month/:day/:title/
source: source
destination: public/
plugins_dir: plugins
code_dir: downloads/code
category_dir: blog/categories

markdown: CommonMark
timezone: UTC
liquid:
  error_mode: strict

commonmark:
  options: ["SMART", "FOOTNOTES", "UNSAFE"]
  extensions: ["strikethrough", "autolink", "table"]

highlighter: none

plugins:
  - jekyll-toc

paginate: 10 # Posts per page on the blog index
paginate_path: "blog/posts/:num" # Directory base for pagination URLs eg. /posts/2/
recent_posts: 5 # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;" # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: "<!--more-->"

titlecase: true # Converts page and post titles to titlecase

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:
# post_asides:
# page_asides:

collections:
  integrations:
    output: true
  examples:
    output: true
  docs:
    output: true
  addons:
    output: true
  faq:
    output: true
  dashboards:
    output: true

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

#Search
algolia:
  api_key: "ba6f7e6d97b3d3d2f778978c742a47c6"

# Twitter
twitter_user: balloob
twitter_tweet_button: true

# Google Analytics
# google_analytics_tracking_id: UA-57927901-1

# Facebook Like
facebook_like: true

social:
  visible: false
  facebook:
    app_id: 338291289691179

  twitter:
    account: home_assistant

  mastodon:
    account: "https://fosstodon.org/@homeassistant"

# Home Assistant release details
current_major_version: 2024
current_minor_version: 2
current_patch_version: 0
date_released: 2024-02-07

# Either # or the anchor link to latest release notes in the blog post.
# Must be prefixed with a # and have double quotes around it.
# Major release:
patch_version_notes: ""
# Minor release (Example #release-0431---april-25):

# Set Front matter defaults
defaults:
  # Defaults for all pages
  - scope:
      path: ""
    values:
      layout: page
      comments: false
      footer: true
      sharing: true
      sidebar: true
      featured: false
  # Defaults for blogs posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      footer: true
      sharing: true
      sidebar: true
  # Enable table of contents for integrations and installations
  #
  # To set toc as a default value, we need to set the scope with an empty path
  # and the collection as type
  # https://github.com/toshimaru/jekyll-toc/issues/116#issuecomment-644205770
  #
  - scope:
      path: ""
      type: integrations
    values:
      toc: true
  - scope:
      path: "installation/*"
    values:
      toc: true
      no_toc: true
  - scope:
      path: "common-tasks/*"
    values:
      toc: true
  - scope:
      path: "hassio/*"
    values:
      toc: true
  # Remove some resources from sitemap
  - scope:
      path: "google*.html"
    values:
      sitemap: false
  - scope:
      path: "static/fonts/**/*.html"
    values:
      sitemap: false
  - scope:
      path: "static/mdi-demo.html"
    values:
      sitemap: false

# Support for files Jekyll will normally exclude
include:
  - "_headers"
  - "_redirects"
  - ".well-known"

# Table of contents
# https://github.com/toshimaru/jekyll-toc
toc:
  min_level: 2 # default: 1
  max_level: 3 # default: 6

# Configuration for installation pages
installation:
  container: "ghcr.io/home-assistant/home-assistant"
  versions:
    python: "3.11"
  types:
    odroid:
      board: ODROID
      installation_media: "eMMC module or SD card"
      variants:
        - name: "ODROID-N2"
          key: "odroid-n2"
        - name: "ODROID-N2+"
          key: "odroid-n2"
        - name: "ODROID-C2"
          key: "odroid-c2"
        - name: "ODROID-C4"
          key: "odroid-c4"
        - name: "ODROID-M1"
          key: "odroid-m1"

    raspberrypi:
      board: Raspberry Pi
      installation_media: "SD card"
      variants:
        - name: "Raspberry Pi 4"
          key: "rpi4-64"
        - name: "Raspberry Pi 3"
          key: "rpi3-64"

    generic-x86-64:
      board: Generic x86-64
      installation_media: "storage device"
      variants:
        - name: "Generic x86-64"
          key: "generic-x86-64"
