[build]
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_BASEURL = "https://www.home-assistant.io/"
HUGO_VERSION = "0.43"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.43"
HUGO_ENABLEGITINGO = "true"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.43"
HUGO_ENABLEGITINGO = "true"

[context.next.enviroment]
HUGO_VERSION = "0.43"
HUGO_ENABLEGITINGO = "true"
